name: Deploying

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          HOSTNAME: ${{ secrets.AWS_HOST }}
          USER_NAME: ${{ secrets.AWS_USER }}
          PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: sh /apps/auto-deploy-expense-mgr.sh
